import type { Metadata } from "next";

import "./globals.css";
import NavBar from "@/components/NavBar";
import { typography } from "@/typography";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={typography.bodyText}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
